### ISSUE TITLE
First authors

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1248]
We already invited a few authors like https://www.youtube.com/user/kreosan and created a test hub for them https://kreosan.wr.io.
We're going to complete the very first version of WRIO OS editor https://core.wrioos.com/?create by the end of August. After that we have to invite authors as much as possible before ICO. Find them on youtube and send them invites.
Create an invitation text and publish it here.
Send ETA.

**Comment by desireedickerson** [comment]
Thoughts?

[WRIO_Cold Connection Invite_20170817.docx](https://github.com/webRunes/WRIO-InternetOS/files/1233268/WRIO_Cold.Connection.Invite_20170817.docx)

**Comment by desireedickerson** [comment]
Hello –

[Insert generic language that shows we are engaged and interested in what our stakeholder is doing; attempt to connect it to WRIO Internet/WebRunes].

WebRunes is changing the way we use the Internet and access information. Rather than learning how to navigate the Internet to find information, the information finds you. Transitioning to Web 3.0, WRIO Internet OS caters to the user, through an open-source, Ethereum-based platform, that proactively pushes tailored semantic data to the user. 

WRIO Internet OS also empowers businesses and social influencers, simplifying outreach to audiences using powerful SEO through semantic page structures. Also, the introduction of monetization and a reward structure for interacting with content, allows users to quickly build crowd funding and revenue streams.

Join us and learn more at [link], while taking part in our ICO by becoming an early adopter. Check out how you can get involved here [link].

We would love to get your audience/user base involved and tell you more about what we are working on at WebRunes with WRIO Internet OS. We can share some content relevant to [whatever the stakeholder is doing]. Happy to send over additional information or chat to discuss how we can partner.

Best,

Thank you for connecting with us.

**Comment by AlexeyAnshakov** [comment]
Thanks. I'll go thorough later. First comments: 
```WRIO Internet/WebRunes```
WRIO Internet OS or WRIO OS
```WebRunes```
webRunes

We must add "First Authors" offer info
https://core.wrioos.com
Author should see what benefits he/she can get working with us. He/she also must see how we help to distribute his/her content via tweets-comments, like
https://getfun.wr.io/

@AlWaleed84 check it out.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 check it out.
