### ISSUE TITLE
Advisory Board

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1267]
Find 3-5 advisors for 1/500 (.2%) / per advisor of our +20% ICO bonus. We need their WP feedback and mention permit on https://webrunes.com/team

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by AlexeyAnshakov** [comment]
Find startups like https://rocketico.io/en/ to contact advisors. Find startups on https://tokenmarket.net/ico-calendar, angel.co and linkedin.

**Comment by ghost** [comment]
There were a few advisors that were put on the linkedin contacts that I added -- I will specifically look for startups on the links above.

**Comment by AlexeyAnshakov** [comment]
Please talk to @AlWaleed84 and start invite them.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
@AlWaleed84 were you able to find any advisors from the list? 

Just cleaning everything up to get up to date - and see what else we need -- do you need an invite email or looking for specific contacts?

LMK

**Comment by AlexeyAnshakov** [comment]
Find advisors at https://icobench.com/experts
and contact them.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
HI Alexey

Do we have an email for our project that I can use - I don't mind using my
own name - but when I contact these people I think its important to have an
email related to the project.

Also what type of advisor are you looking for?
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
I believe the best option is to contact them on linkedin. If they have an email only, please send me email text and addresses. @AlWaleed84 please help Jillian with the criterias.

**Comment by AlexeyAnshakov** [comment]
progress?

**Comment by ghost** [comment]
Hi alexey I’ve been in touch with a few on LinkedIn 

Are we offering any type of compensation?

**Comment by AlexeyAnshakov** [comment]
As it described in the very beginning of the issue. @AlWaleed84 please help Jillian with it.

**Comment by AlWaleed84** [comment]
Will be talking with Jillian soon. 

AlWaleed K.

**Comment by AlexeyAnshakov** [comment]
https://www.linkedin.com/in/tokyotony

**Comment by AlexeyAnshakov** [comment]
https://www.linkedin.com/in/tokyotony
https://www.linkedin.com/in/dmitrymishunin/
https://www.linkedin.com/in/vladimir-nikitin-bb6154ba

**Comment by ghost** [comment]
Hey Waleed -- Let's jam on this this weekend :) @AlWaleed84

**Comment by ghost** [comment]
@AlexeyAnshakov @AlWaleed84 

I've reached out to about 30 people who have "advisor" on LinkedIn - but without much interest.

What is the progress on this?

**Comment by AlexeyAnshakov** [comment]
We have to proceed. Please check advisors on others related ICO websites and contact them.
BTW, please publish the template text that you used.

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
ETA?
Look advisors on linkedin by tag "semantic web".

**Comment by AlexeyAnshakov** [comment]
Check others ICOs websites like https://jincor.com and contact theirs Advisors. But first of all contact https://icobench.com/experts

**Comment by AlexeyAnshakov** [comment]
>Find advisors at https://icobench.com/experts
and contact them.

Also propose them (up to 5 in total) a 25,000 WGD reward (eq. ~$1,000) for a recommendation that we'll publish on wrioos.com

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by AlWaleed84** [comment]
Currently reaching out to these— academics, big data scientist, or machine learning experts. 

- https://www.linkedin.com/in/rubenverborgh
- https://www.linkedin.com/in/fabio-ricci-419b221a
- https://www.linkedin.com/in/naila-karim-6a155a54
- https://www.linkedin.com/in/artem-nabirkin-a6264b38
-https://www.linkedin.com/in/semanticwebarchitect
- https://www.linkedin.com/in/costezki
- https://www.linkedin.com/in/jordanjordancohen
- https://www.linkedin.com/in/stuartsutton
- https://www.linkedin.com/in/literarymachine
- https://www.linkedin.com/in/tereshkov
- https://www.linkedin.com/in/andy-aliko-a7085472
- https://www.linkedin.com/in/donald-baker-5b58b516
- https://www.linkedin.com/in/eleftherios-karapetsas-1a18b919
- https://www.linkedin.com/in/abhishek-singh-5622757
- https://www.linkedin.com/in/alexandr-honchar-4423b962
- https://www.linkedin.com/in/fengzhu
- https://www.linkedin.com/in/taweh-beysolow-ii-59982760
- https://www.linkedin.com/in/andreas-pfadler-6a84ba1a
- https://www.linkedin.com/in/ashish9112
- https://www.linkedin.com/in/jalammar
- https://www.linkedin.com/in/lctpalmer
- https://www.linkedin.com/in/yitzhak-spielberg-looking-for-my-next-challenge-6800b655
- https://www.linkedin.com/in/choukha
- https://www.linkedin.com/in/ravitejakankanala
- https://www.linkedin.com/in/kwokmichael
- https://www.linkedin.com/in/matt-wilder-phd-6b3aa282


AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
@benjamin421 please find people like this one
https://twitter.com/aradchenko1
Create a list and coordinate with Waleed to reach them out.

**Comment by consciousrepo** [comment]
Will do

**Comment by consciousrepo** [comment]
https://www.linkedin.com/in/eric-sebastien-dechaux/ New connection I've been going back and forth with on Telegram, very interested in our project.

**Comment by AlexeyAnshakov** [comment]
Sounds good. Please Make a call with Eric and Waleed to discuss details.

**Comment by ericegnet** [comment]
I have also started process of researching advisors for the team. I'm happy to speak with Eric Sebastien when it makes sense. I know AlWaleed intends to speak with him first.

**Comment by AlWaleed84** [comment]
There’s a few on my radar that I’m holding off talking to until the end of the week, but yes— I don’t mind including Sabastien in that list as well. 


AlWaleed K. AlShehail

**Comment by RoySasson** [comment]
If possible, please record your conversation with Eric Sebastien , would be helpful for future discussions with other optional partners

**Comment by consciousrepo** [comment]
Here's Eric's Telegram as well if it makes it easier to make contact @Eric_vibeo

**Comment by AlWaleed84** [comment]
Oh I assumed he might have been vaguely interested through LinkedIn.  In that case, we should talk to him now. 


AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
Yeah, we just went back and forth a few times directly on Telegram after connecting on linked-in but he has not been active on telegram recently.

**Comment by RoySasson** [comment]
If we will have him (or someone like him)  as an adviser, what would be his
added value ? The extra validation it will give our ICO by having a key
figure listed as an adviser  ?

2018-04-04 21:49 GMT+02:00 Benjamin Anderson <notifications@github.com>:

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 please start
```
Find advisors at https://icobench.com/experts
and contact them.
```
with @RoySasson. So we can use their help to get rating as well.

**Comment by consciousrepo** [comment]
@RoySasson I was most impressed by what he claimed to be able to bring to the table in his bio, check out his linkedin, he has a list in his bio

**Comment by RoySasson** [comment]
I have scheduled a call for tomorrow with an adviser I know, will try to get him to co-op with us. 
He has been involved with few other ICOs , hope he will agree to do a token based agreement.
https://www.linkedin.com/in/ram-avissar-adv-cpa-20482b84/
https://www.bitsme.io/

**Comment by AlexeyAnshakov** [comment]
Great. Perhaps he can help with linkedin groups like "ICO- Unicorn Hunters - Network" and others, in his list of interest.

**Comment by consciousrepo** [comment]
Here are the terms Send by Jun who I introduced in slack #general a few moments ago, I told him we are mainly seeking to compensate advisors post crowd-sale which he had no issue with although obviously he prefers eth upfront which I said was highly unlikely and also that we would send him a counter offer after discussion with the team. 
"Heres my engagement and my proposed remuneration

1. Design telegram new airdrop + bounty system to make it more viral
2. Grow community to at approximately 20k strong
3. Help gather funds from my private investors (but no promises because now market pretty down but I will try
4. Help with the token mechanics
5. Review the whitepaper to further tighten it up
6. Even after project, will help to push out your projects in my different channels to create volume for your token - https://t.me/CryptoAnalysisTM being my main
7. I’m also a community leader for Huobi.pro (2nd biggest exchange globally) and I can try to help you guys get listed after the ICO (no guarantee because they are quite strict).

https://t.me/KinguinICOPublic is one of the project I am active in doing their white paper + build their group from 300 to 33,000 now. We won the "BEST ICO" in Berlin cryptocurrency summit and also 1st runner up in the recent Global Blockchain Competition. Links are below if you wanna see. Sakae holdings ICO (Public listed company in Singapore) also requested for advisory from my side as well because they seen my work which I will be taking on as well (just for marketing and community building and white paper review)

https://medium.com/@KinguinOfficial/kinguin-io-wins-best-ico-project-2018-at-cryptocurrency-world-expo-a7cb4e99fdcf

https://medium.com/@KinguinOfficial/kinguin-io-places-2nd-at-global-blockchain-competition-28c933e480f6

My team’s results:

https://t.me/KinguinICOPublic (33,000)

https://t.me/BTUCommunity (32,000)  

https://t.me/LendoPlatform
(23,000)

https://t.me/axens_chat (23,000) 

https://t.me/agentnotneededofficial (22,000)

https://t.me/rootblockchain (16,000) 

https://t.me/owndata_network (15,000) 

Remuneration: 10 ETH upfront + 0.5% of total funds raised."

**Comment by ghost** [comment]
Not bad 

I think we need to consider the listing on exchanges though as the selling point

**Comment by consciousrepo** [comment]
I agree, like we mentioned in the last meeting, that'd be a key variable to look for in an advisor, also, he's located in Singapore and most of his network is in that part of the world, an area where we lack any team members. plus If he's able to grow our following that dramatically as well, we would be able to offer cross promotion with much bigger telegram pages once our following is bigger as well

**Comment by AlexeyAnshakov** [comment]
Not sure how he's going to achieve telegram growing.

**Comment by ghost** [comment]
Ask him
ᐧ

j.

**Comment by consciousrepo** [comment]
His answer:

> > To help gain traction in building telegram community, I propose that we do an airdrop system which i will push out using my network and reach. 0 marketing cost required. Simple reasons why.
> 
> 1) to build following on telegram
> 
> 2) to get good rating on ICO drops, ICO bench, ICO rating etc. For example, one of the group i built was agentnotneeded. We were given 4.5/5 on icobench. Size of telegram group is one of the factors.
> 
> 3) to get listed on exchange like binance and huobi (which i have contacts in as i’m the community leader of Huobi - but no promises because Huobi has certain requirements but i can help push for it) after ICO. They look at telegram group size.
> 
> 4) research have shown that the size of telegram group determines roughly how much a ICO will raise. More members = more funds raised.
> 
> We can create the airdrop tab on our website to for people.
> 
> Few items required from them
> 
> 1. Telegram ID
> 2. ERC20 wallet address
> 3. UNIQUE REFERRAL LINK
> 4. We need them to join our telegram group (provide a link for them to join)
> 5. Email address (to store for our mailers)
> 
> So you can airdrop $10 USD per person and we will cap it for only the first 30,000 who joined the telegram chat. We will only be using tokens and not actual USD.
> 
> If they refer a friend, they will get $10 + $5 (ref fees). So basically per cost of acquisition is made to be around $15 in tokens.
> 
> This will cost us almost nothing (because its in tokens) + will help gain adoption because people would have our wallets in their account (:
> I have alot of crypto databases

**Comment by AlWaleed84** [comment]
Thanks Ben. He seems very young for an advisor though, does he have a LinkedIn?  I’m curious what he did exactly for kinguin.io



AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
https://www.linkedin.com/in/ongjunhao/ here it is, and I agree and was concerned with age too but if his work speaks for itself then that shouldn't be a deciding variable

**Comment by AlWaleed84** [comment]
His responses are good though.



AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
Right, not vague like alot of other advisors and he's been backing all of his claims with examples of past work

**Comment by AlexeyAnshakov** [comment]
He's not an advisor but GH.

**Comment by ghost** [comment]
An advisor with many different hats
ᐧ

j.

**Comment by consciousrepo** [comment]
He lists his past experiences in advisory roles although it does appear most of his roles with past ICO's have been to initiate growth under the advisor umbrella

**Comment by consciousrepo** [comment]
I'm seeing on his LinkedIn he presented at the cryptocurrency world expo on behalf of Kinguin @AlWaleed84 in regards to his work with them

**Comment by AlWaleed84** [comment]
If he knows Reddit well enough— he can be a community based Advisor.  However, if you managed to gently persuade him in a role instead, I’d suggest we ask him what role he’s interested in besides that.  



AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
Like perhaps a hard role as Growth Hacker since we don't have one yet rather than on the team as an advisor whose main function is growth hacking and getting the ico listed?

**Comment by ghost** [comment]
Bingo

**Comment by consciousrepo** [comment]
Let's discuss terms then so I can come to him with a hard proposition, maybe even a contract. Although I just shot him a message seeing If he'd be interested in a hard role rather than advisor so we can wait to see if that's even what he's looking for. Either way, If he can deliver i think we could benefit from his network greatly

**Comment by consciousrepo** [comment]
He's interested in a hard position.

**Comment by RoySasson** [comment]
What about a trial period , will he agree on that ? 
We can determine goals and see if can meet them in a week or so . Goals like acciving X new users to our telegram, FB etc. , he can decide what way he wants to push it ( with our supervision so our brand won't be harmed in any way ) and that way we will be able to examine his skills as GH .

**Comment by consciousrepo** [comment]
We can structure his contract the same way as ours or at least how mine was where they are a full team member but the contract is not binding until 21 days in to validate efforts and see if it's a good fit?

**Comment by AlWaleed84** [comment]
Yeah— that’s how it is with everyone Ben.

Good to know. 


AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
Cool, @AlWaleed84 do you have time for a quick call regarding whether/how to move forward with Jun?

**Comment by AlWaleed84** [comment]
Yeah— I’ll call you.


AlWaleed K. AlShehail

**Comment by RoySasson** [comment]
Today I talked to another potential partner :
https://www.linkedin.com/in/azriel-arad-a9b0071b/
He works for http://maico.io/ . 
What benefits do you find in his company that could assist us the most , so I'll be able to have a targeted discussion with him ? 
He's willing to consider past-ico token payment.

**Comment by RoySasson** [comment]
The way I see it , we gonna have many more advisers willing to co-op , and we need to see how we can get the most out of them . We can't add everyone as a partner or adviser, but we do want to be able to benefit from all of them.

The options we'll have as I see it :
1. Through our affiliate program- letting the partner promoting and posting with a referral link and gaining %  
2. Adviser bounty program 
we can add section to our site : "Experts Reviews" - the adviser would write review about our product\ico, which we will publish on our site.By doing that you must remember and "sell it" that he will benefit a further exposure to his own advisory services , as a reputable ico like wrio considers his opinion to an important one. 
The adviser will share the review in his SM . 
Since it's a one time effort by his side to writing the review , he will be getting 10k WGD , and needs to remember that it's a long time investment .

I wrote in general , but I hope you can see my point here to try maximizing benefits from every contact we make

**Comment by consciousrepo** [comment]
Seems like a good low risk way to reap the most reward. I agree with that point @RoySasson to reap from all contacts. We should brainstorm an exact structure

**Comment by consciousrepo** [comment]
@adm_crew is a potential advisor, not good enough to bring on the team but who'd participate in Roy's suggested program with enthusiasm

**Comment by AlexeyAnshakov** [comment]
```
Find advisors at https://icobench.com/experts
and contact them.
```
Have you already started contacting them?

**Comment by consciousrepo** [comment]
Not from that list no, been waiting to fine tune LP and official launch to start that list, just casually connecting with advisors on LinkedIn and making conversation on telegram to build contacts and gain insights

**Comment by RoySasson** [comment]
Have you already started contacting them?

contacted Simon Cocking and Taylor Sanfrod - 1# ranked ico advisor and the second is in the first 20 rated advisors 
https://www.linkedin.com/in/tylersanford/
https://www.linkedin.com/in/simon-cocking-20540135/
Will update on discussions , these guys gets lots of new requests like mine , won't be so easy ...

**Comment by RoySasson** [comment]
Here's Simon's replay :

Re working with you guys on advisory board, it's usually to help with promotion, endorsement, strategy, media advice and insights from 100+ other successful ICO campaigns I have worked on. In exchange for a fee, a token allocation, and a % of the funds raised from the token sale. ICOs that I have worked with & successfully raised their targets include -> Covesting, Iungo, ClearPoll, Hydropower, Zloadr, Seratio, DEScrow and then the next wave are all post preICO and currently into main ICO phase Freindz, Synchfab, Moonlighting, X8Currency, Moonlite, Elpis, Asset token, among others, and another batch going to pre ICO soon. (Also did PR work for Credits, KickICO, Hacken, MicroMoney, Sharpe Capital, Nebeus, Naga Group, Swissborg and Ties.Network). Ok, quick follow up questions. When would you like me to start working with you, for how long, and in which areas would you like me to advise and assist? Great. I'm normally paid an introductory fee, a token allocation, and then a % of the funds raised from the token sale. Welcome to email me here simon@irishtechnews.ie to discuss further. Re fee it is normally an introductory fee of €10,000 or ether equivalent, a token allocation to be decided with you, and 1 % of the funds raised from the token sale. Thanks Simon FYI I don't do token only offers because I could do a lot of work, and then if you don't hit your target I will have given all my time for nothing (it has happened).  This is some, but not all, of what I do. Every advisory role is personally adapted to fit the needs of each ICO. Overall I help with promotion, endorsement, strategy, media advice and insights from over 105 other successful ICO campaigns I have worked on.  As the top ranked ICO advisor on ICObench https://icobench.com/people if I work with you it will bring you a lot of good publicity. Review the website / whitepaper / project.  Provide strategic guidance to the marketing team  Advise on how to kick start / rapidly grow community engagement, i.e. social channels, chat (Telegram), forums (BitcoinTalk), etc. To get people to buy into and support the project, organic growth Help with media coverage Assist you in getting media coverage (e.g. Irish Tech News, CryptoCoin.news, etc.) Broker intros for potential partnerships (strategic, e.g. in blockchain, and for the token sale) List as an advisor and on LinkedIn, 27,000 followers Leverage my network (Linkedin + 120,000 on Twitter) and experience to make the ICO a success

**Comment by AlexeyAnshakov** [comment]
I don't believe his services are worth $10k. We can spend $ much better.

**Comment by consciousrepo** [comment]
Definitely seems like a star player, but I agree, 10,000$ is way to steep, money can be allocated much more effectively, we'd be better off utilizing the advisor affiliate program you suggested on multiple advisors reaping small benefit from many at low risk than dropping 10k on one advisor, plus we are in the final stages of closing negotiation with Jun who's following, granted is smaller, however he promises the same level of growth and ICO listing connections at less than half the rate and has been a very public figure on multiple other projects so we will receive similar credibility with him although granted probably not as much as having the #1 rated advisor from ico bench.

**Comment by RoySasson** [comment]
As you said , the #1 advisor will bust our credibility to the top level and has more than 10 times followers than Jun . 
Should I bargain to try hit 5000$ or move on ? 

----- הודעה מקורית -----
מאת: "Benjamin Anderson" <notifications@github.com>
נשלח: ‎13/‎04/‎2018 20:55
אל: "webRunes/WRIO-InternetOS" <WRIO-InternetOS@noreply.github.com>
עותק: "Roy Sasson" <roeysa@gmail.com>; "Mention" <mention@noreply.github.com>
נושא: Re: [webRunes/WRIO-InternetOS] Advisory Board (#1267)

Definitely seems like a star player, but I agree, 10,000$ is way to steep, money can be allocated much more effectively, we'd be better off utilizing the advisor affiliate program you suggested on multiple advisors reaping small benefit from many at low risk than dropping 10k on one advisor, plus we are in the final stages of closing negotiation with Jun who's following, granted is smaller, however he promises the same level of growth and ICO listing connections at less than half the rate and has been a very public figure on multiple other projects so we will receive similar credibility with him although granted probably not as much as having the #1 rated advisor from ico bench.

**Comment by AlexeyAnshakov** [comment]
We should try to contact others in the icobench list and find who accept tokens only.

**Comment by consciousrepo** [comment]
Well if he can match at 5000 that's a different story and could definitely be worth it, If you think you can lower him to that level, I'd definitely try @RoySasson , we haven't closed with Jun yet, right now we're at 4,700 in his negotiations.

**Comment by consciousrepo** [comment]
> We should try to contact others in the icobench list and find who accept tokens only.

And do this simultaneously

**Comment by RoySasson** [comment]
He is willing to consider it , will keep discussing with him and maybe will add him as we did with Jun to telegram 

----- הודעה מקורית -----
מאת: "Benjamin Anderson" <notifications@github.com>
נשלח: ‎13/‎04/‎2018 21:14
אל: "webRunes/WRIO-InternetOS" <WRIO-InternetOS@noreply.github.com>
עותק: "Roy Sasson" <roeysa@gmail.com>; "Mention" <mention@noreply.github.com>
נושא: Re: [webRunes/WRIO-InternetOS] Advisory Board (#1267)

Well if he can match at 5000 that's a different story and could definitely be worth it, If you think you can lower him to that level, I'd definitely try @RoySasson , we haven't closed with Jun yet, right now we're at 4,700 in his negotiations.

**Comment by AlexeyAnshakov** [comment]
In fact, i'm not sure that he's worth even 5k. He's just an advisor, not many users will dig too deep and for them won't be very imprtant his participation. I'd focus on pure tokens advisors.

**Comment by RoySasson** [comment]
Will focus on that, np 

----- הודעה מקורית -----
מאת: "Alexey Anshakov" <notifications@github.com>
נשלח: ‎14/‎04/‎2018 15:14
אל: "webRunes/WRIO-InternetOS" <WRIO-InternetOS@noreply.github.com>
עותק: "Roy Sasson" <roeysa@gmail.com>; "Mention" <mention@noreply.github.com>
נושא: Re: [webRunes/WRIO-InternetOS] Advisory Board (#1267)

In fact, i'm not he worth even 5k. He's just an advisor, not many user will dig too deep and for them won't be very imprtant his participation. I'd focus on pure tokens advisors.

**Comment by AlWaleed84** [comment]
Hey, did anyone contact that legal advisor that was linked here? Or should I contact him?   Lost track of where it was because of the messages crowding. 


AlWaleed K. AlShehail

**Comment by ghost** [comment]
​I haven't - maybe just do it ​
ᐧ

j.

**Comment by consciousrepo** [comment]
I connected but sent no introduction message if you'd like to reach out

**Comment by AlexeyAnshakov** [comment]
What progress?

**Comment by AlexeyAnshakov** [comment]
@JamesDylan please push it according
>As far as advisors go - I suggest approaching other ICOs that have recently completed. We can use their blockchain people as advisors because they'll have proven experience. And being a recently completed ICO means they'll probably have recent private investor contacts too
