### ISSUE TITLE
Landing

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1457]
Use the One-liner chapter https://bitcointalk.org/index.php?topic=3013546. WRIO Internet OS Story: 
Imagine an easy-to-use, privacy respectful and browser-based open-source operating system with blockchain-powered cloud apps enabled in a click that use public decentralized storage of machine-readable Linked Data. This allows automatic data processing of all information uploaded into web based on your interests. Now, that is what WRIO Internet OS is.

What (Decentralized semantic user-centric web 3.0 platform powered by the blockchain) -> Why -> How [Semantics] -> a blockchain-poswered decentralized machine-readable data pool [structured data] (magic souce) -> Automatic data processing -> Benefits -> User-centric browsing experience -> Web 3.0 -> why to participate (vision) & how, facts about the proj

**Comment by consciousrepo** [comment]
https://bba4211998.wixsite.com/wrioospreview
Here's the preview as of now, I'll keep republishing it at this same address so everyone can overview the progress and give commentary/input

**Comment by AlexeyAnshakov** [comment]
Why do you continue to edit this template? Use landing.wrioos.com

**Comment by consciousrepo** [comment]
Who's the webhost to access that site so I can log in to edit or should I just alter the html as you have it in github? My html experience is lacking, the platform I'm using integrates front and backend development which Is why I've been building it through there and once it's finished we can attach it to that domain.

**Comment by consciousrepo** [comment]
http://www.evariant.com/
https://www.nordicwi.com/
https://friendup.cloud/
These are the 3 sites Eric sent me to take inspiration from in building the page, I'm trying to maintain the linear format and mix and match the most appealing aspects of each

**Comment by AlexeyAnshakov** [comment]
No, prob. Create a text version of each slide. Invitation has been sent.

**Comment by ghost** [comment]
Quite lovely :) -- Once it is ready for proof reading LMK and I will go
through it
ᐧ

j.

**Comment by consciousrepo** [comment]
I spoke with Eric yesterday, he likes the side scroll layout for use as a landing page exclusively for a campaign so I also went ahead and finished the home page for the draft on the other and he was fond of it but said it needed more contrasting color and more condensed information in bigger text rather than more text to convey an idea or facts. Heres the preview link again, happy to hear any more constructive criticisms to output the best page(:
https://bba4211998.wixsite.com/wrioospreview

**Comment by consciousrepo** [comment]
Can we close this issue?
